const CSV_HEADER_TEMPLATE = [
  'nome',
  'numero_documento',
  'email',
  'valor',
  'vencimento',
  'observacao',
  'seu_numero',
  'descricao',
  'juros_por_mes',
  'multa',
  'dias_baixar_boleto_apos_vencimento',
  'desconto',
  'desconto_ate',
  'valor_de_abatimento',
  'abatimento',
  'natureza',
  'cedente',
  'cedente_numero_inscricao',
  'pagador_telefone',
  'endereco_cep',
  'endereco_logradouro',
  'endereco_numero',
  'endereco_complemento',
  'endereco_bairro',
  'endereco_municipio',
  'endereco_uf',
  'desconto_ate_2',
  'desconto_2',
  'desconto_ate_3',
  'desconto_3',
];

export default CSV_HEADER_TEMPLATE;